// <auto-generated />
using ColegioOpcaoA.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ColegioOpcaoA.Repositorio.Migrations
{
    [DbContext(typeof(ColegioOpcaoAContexto))]
    partial class ColegioOpcaoAContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColegioOpcaoA.Dominio.Entidades.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Media");

                    b.Property<bool>("MelhorAluno");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("StatusAluno");

                    b.Property<int>("TurmaId");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ColegioOpcaoA.Dominio.Entidades.Prova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlunoId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Nota");

                    b.Property<double>("Peso");

                    b.Property<int>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("ColegioOpcaoA.Dominio.Entidades.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("ColegioOpcaoA.Dominio.Entidades.Aluno", b =>
                {
                    b.HasOne("ColegioOpcaoA.Dominio.Entidades.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ColegioOpcaoA.Dominio.Entidades.Prova", b =>
                {
                    b.HasOne("ColegioOpcaoA.Dominio.Entidades.Aluno", "Aluno")
                        .WithMany("Provas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
